name: Build image

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: ko-build/setup-ko@v0.6
      - run: |
          tag=$(echo ${{ github.sha }} | cut -c-8)
          ko build --bare --platform=linux/arm64,linux/amd64 --sbom=none -t latest -t ${tag}
